# Generated by Django 4.0.4 on 2022-05-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customer_profile_pic_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='topic',
        ),
    ]
