# Generated by Django 4.0.4 on 2022-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_quiz_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
